<a href="https://colab.research.google.com/github/tireless-22/AI_LAB/blob/main/AI_LAB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

AI LAB

WEEK1


In [52]:
import numpy as np

import pandas as pd

a. To generate an array of random numbers from a normal distribution for the array of a
given shape

In [53]:
a=np.random.randint(1,100,20)
# Here we generated 20 values in between the 1 and 100
print(a)

[35 23 91 71 32 14 72 32 87 30 65 50 71 53 57 98 32 19 94 16]


b. Implement Arithmetic operations on two arrays (perform broadcasting also

In [54]:
normalList_a=[1,2,3,4]
normalList_b=[5,6,7,8]
# a is list here
numpyArray_a=np.array(normalList_a)
numpyArray_b=np.array(normalList_b)
# print(type(numpyArray_a))

# addition
print("addition")
print(numpyArray_a+numpyArray_b)

# substraction
print("substraction")
print(numpyArray_a-numpyArray_b)

# multiplication
print("multiplication")
print(numpyArray_a*numpyArray_b)

# division
print("division")
print(numpyArray_a/numpyArray_b)



addition
[ 6  8 10 12]
substraction
[-4 -4 -4 -4]
multiplication
[ 5 12 21 32]
division
[0.2        0.33333333 0.42857143 0.5       ]


c Find minimum, maximum, mean in a given array. ( in both the axes )

In [55]:
a=np.random.randint(10,30,20)
print("generated array")
print(a)
print("minimum")
print(a.min())
print("maximum")
print(a.max())
print("mean")
print(a.mean())

generated array
[11 23 22 29 18 14 20 26 11 13 28 13 12 14 28 22 23 28 14 10]
minimum
10
maximum
29
mean
18.95


d. Implement np.arange and np.linspace functions. 

In [56]:
# Arrange


# first value is start and second is end
# 3rd one is jump
# 1st value is inclusive
# 2nd value is exclusive
a=np.arange(10)
print(a)
print()
b=np.arange(1,51,2)
print(b)

[0 1 2 3 4 5 6 7 8 9]

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


In [57]:
# linespace

# both the start and end are inclusive
# first value is starting value and
# second value is the ending value
# third one is no of samples,but it is optional
# defaultly it is set to 50 samples
# to know the step of the values,find the difference between the consecutive values

a=np.linspace(2,9)
print("created array")
print(a)
print()
print("step in the array")
print(a[1]-a[0])


created array
[2.         2.14285714 2.28571429 2.42857143 2.57142857 2.71428571
 2.85714286 3.         3.14285714 3.28571429 3.42857143 3.57142857
 3.71428571 3.85714286 4.         4.14285714 4.28571429 4.42857143
 4.57142857 4.71428571 4.85714286 5.         5.14285714 5.28571429
 5.42857143 5.57142857 5.71428571 5.85714286 6.         6.14285714
 6.28571429 6.42857143 6.57142857 6.71428571 6.85714286 7.
 7.14285714 7.28571429 7.42857143 7.57142857 7.71428571 7.85714286
 8.         8.14285714 8.28571429 8.42857143 8.57142857 8.71428571
 8.85714286 9.        ]

step in the array
0.1428571428571428


e. Create a pandas series from a given list


In [58]:
normalList_a=np.linspace(2,9)

numpyArray_a = pd.Series(normalList_a)

print(numpyArray_a)

0     2.000000
1     2.142857
2     2.285714
3     2.428571
4     2.571429
5     2.714286
6     2.857143
7     3.000000
8     3.142857
9     3.285714
10    3.428571
11    3.571429
12    3.714286
13    3.857143
14    4.000000
15    4.142857
16    4.285714
17    4.428571
18    4.571429
19    4.714286
20    4.857143
21    5.000000
22    5.142857
23    5.285714
24    5.428571
25    5.571429
26    5.714286
27    5.857143
28    6.000000
29    6.142857
30    6.285714
31    6.428571
32    6.571429
33    6.714286
34    6.857143
35    7.000000
36    7.142857
37    7.285714
38    7.428571
39    7.571429
40    7.714286
41    7.857143
42    8.000000
43    8.142857
44    8.285714
45    8.428571
46    8.571429
47    8.714286
48    8.857143
49    9.000000
dtype: float64


f. Create pandas series with data and index and display the index values

In [59]:
dff=pd.DataFrame()
n=int(input("enter the no of columns"))
m=int(input("no of rows"))

lower_limit=int(input("enter_lower_limit"))
upper_limit=int(input("enter_right_limit"))


temp=65
for i in range(m):
  dff[chr(temp+i)]=np.random.randint(lower_limit,upper_limit,n)


print(dff)

enter the no of columns20
no of rows20
enter_lower_limit1
enter_right_limit100
     A   B   C   D   E   F   G   H   I   J   K   L   M   N   O   P   Q   R  \
0   37   1  71  52  61  24  72  86  95  85  38  81   2  60  65  85  76  68   
1   89  12  23  66  31  44  19  44  10  48  23  56  46  72  89  94  28  47   
2   85  55  75  43  48  68  53   8  25  61  53  57  11  19  91  57  76  39   
3   11  15  17  34  84  50  14   5   3  32  24  28  48   8  82  45  84  41   
4   85  16  28  35  93   5  88  51  98  77  37  50   4  12   4  78  84  10   
5   85  97  95  62   4  52   5  15   8  73  10  27  36  29  19  45  24  16   
6   76  14  18  53  92   9  84  46  64  33  98  19  49  79  20  71  61  40   
7    6  44  57  41  19  49  35  55  27  44  13  27  10  66  58  46  46  42   
8   66  29  37  39  95  54  37  83  92  13  50  81  34  17  38  67  65  19   
9   82  63  34  94  27  65  46  29  72  62  90  35  99  57   2  92  78  18   
10  97  98  83  43  43  41  82  21  41   1  90  82  99  61  43 

g. Create a data frame with columns at least 5 observations

i. Select a particular column from the DataFrame

ii. Summarize the data frame and observe the stats of the DataFrame created

iii. Observe the mean and standard deviation of the data frame and print the values. 


In [63]:
# use that dff here

randColIndex=np.random.randint(0,n)
print("picked random column number",randColIndex)
print()

print("printing that picked random column")

print(dff[chr(65+randColIndex)])



picked random column number 4

printing that picked random column
0     61
1     31
2     48
3     84
4     93
5      4
6     92
7     19
8     95
9     27
10    43
11    60
12    15
13    98
14    54
15    47
16    16
17    88
18     9
19    84
Name: E, dtype: int64


In [61]:
print("description about the data that we have")
print()

print(dff.describe())

description about the data that we have

               A          B          C          D          E          F  \
count  20.000000  20.000000  20.000000  20.000000  20.000000  20.000000   
mean   56.550000  46.750000  38.400000  58.000000  53.400000  40.050000   
std    30.819466  31.004032  27.434899  24.473401  32.277416  20.811118   
min     2.000000   1.000000   6.000000  16.000000   4.000000   1.000000   
25%    41.500000  15.750000  17.750000  40.500000  25.000000  30.000000   
50%    63.500000  41.500000  31.000000  52.500000  51.000000  42.500000   
75%    82.750000  69.000000  59.750000  82.750000  85.000000  54.500000   
max    97.000000  98.000000  95.000000  95.000000  98.000000  70.000000   

               G          H          I          J          K          L  \
count  20.000000  20.000000  20.000000  20.000000  20.000000  20.000000   
mean   42.200000  40.500000  53.750000  51.550000  49.200000  55.700000   
std    27.450626  24.433583  33.738741  26.073731  32.9155

In [62]:
print("printing means")
print()
print()
print(dff.mean())

printing means


A    56.55
B    46.75
C    38.40
D    58.00
E    53.40
F    40.05
G    42.20
H    40.50
I    53.75
J    51.55
K    49.20
L    55.70
M    45.50
N    48.85
O    44.55
P    61.45
Q    58.85
R    46.85
S    57.90
T    50.30
dtype: float64
